import Layout from "@/components/Layout/Layout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div className="flex flex-col h-full bg-slate-800 p-4 text-white">
            <h1 className="text-4xl font-mono">
              Learning Frontend Development
            </h1>
            <h2 className="font-mono">
              This is the place for you to learn all Frontend Development
            </h2>
          </div>
        </Layout>
      </main>
    </>
  );
}
